HPCC-11273 Changes to backupnode service
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

diff --git a/initfiles/bin/init_backupnode.in b/initfiles/bin/init_backupnode.in
--- a/initfiles/bin/init_backupnode.in
+++ b/initfiles/bin/init_backupnode.in
@@ -45,67 +45,73 @@ done
 
 which_pidof
 
-while true; do
-    sleep ${interval}h
-    log "------------------------------"
-    log "starting backupnode job..."
+# backup function
+# parameters:
+#1 target
+function backup()
+{
+    exec 2>@LOG_PATH@/${component}/${target}.debug
+    set -x
+    local target=${1}
+    #safe as background job in subshell
+    cfg.section.${target}
 
-
-    for target in ${thorlist[@]}; do
-        log "performing backup on target cluster : ${target}"
-        cfg.section.${target}
-        backupnode_data=$(@EXEC_PATH@/updtdalienv @CONFIG_DIR@/@ENV_XML_FILE@ -d data backupnode ${target})
-        if [[ -z "$backupnode_data" ]]; then
-            log "cannot determine backupnode directory for ${target}"
+    while true; do
+        sleep ${interval}m
+        log "${header} Starting backup of cluster"
+        local backupnode_data=$(@EXEC_PATH@/updtdalienv @CONFIG_DIR@/@ENV_XML_FILE@ -d data backupnode ${target})
+        if [[ -z "${backupnode_data}" ]]; then
+            log "${header} Cannot determine backupnode directory"  
             break
         fi
-
-        // fetch thorgroup slave machines from dali
-        @EXEC_PATH@/daliadmin server=$daliserver dfsgroup ${target} @RUNTIME_PATH@/${target}/backupnode.slaves
+        # Fetch thorgroup slave machines from dali
+        @EXEC_PATH@/daliadmin server=$daliserver dfsgroup ${target} @RUNTIME_PATH@/${component}/${target}.slaves
         if [[ $? != 0 ]]; then
-            log "failed to lookup dali group for $target"
+            log "${header} Failed to lookup dfsgroup"
             break
         fi
+        backupnode_data=${backupnode_data}/${target}/last_backup
+        local backupnode_remotedata=//${thormaster}$backupnode_data
 
-        backupnode_data=$backupnode_data/${target}/last_backup
-        if [[ "$localthor" == "true" ]]; then
-            backupnode_remotedata=$backupnode_data
-        else
-            backupnode_remotedata=//${thormaster}$backupnode_data
-        fi
+        mkdir -p ${backupnode_data}
+        rm -f ${backupnode_data}/*.ERR
+        rm -f ${backupnode_data}/*.DAT
 
-        mkdir -p $backupnode_data
-        rm -f $backupnode_data/*.ERR
-        rm -f $backupnode_data/*.DAT
+        log "${header} Using backupnode directory $backupnode_data"
+        log "${header} Reading slaves file @RUNTIME_PATH@/${component}/${target}.slaves"
+        log "${header} Scanning files from dali ..."
 
-        log "Using backupnode directory $backupnode_data"
-        log "Reading slaves file @RUNTIME_PATH@/${target}/backupnode.slaves"
-        log "Scanning files from dali ..."
-
-        nodegroup=$thorprimary
+        local nodegroup=${thorprimary}
         if [[ -z "$thorprimary" ]]; then
-            nodegroup=$thorname
+            nodegroup=${thorname}
         fi
 
-        @EXEC_PATH@/backupnode -O $daliserver $nodegroup $backupnode_data >> $logfile 2>&1
+        @EXEC_PATH@/backupnode -O ${daliserver} ${nodegroup} ${backupnode_data} >> ${logfile} 2>&1
         if [[ $? -ne 0 ]]; then
-            log "Backupnode of ${target} failed - see ${logfile}"
+            log "${header} Backupnode failed"
             break
         fi
-
         # maximum number of threads frunssh will be permitted to use (capped by # slaves)
         MAXTHREADS=1000
 
-        frunssh @RUNTIME_PATH@/${target}/backupnode.slaves "killall backupnode 1>/dev/null 2>&1" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$MAXTHREADS -b >> $logfile 2>&1
-        log "frunssh @RUNTIME_PATH@/${target}/backupnode.slaves \"/bin/sh -c 'mkdir -p @LOG_PATH@; mkdir -p @RUNTIME_PATH@; @EXEC_PATH@/backupnode -T -X $backupnode_remotedata %n %c %a %x $2 > @LOG_PATH@/backup_node_%n_${logpthtail}.log 2>&1'\" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$MAXTHREADS -b >> $logfile 2>&1"
-        frunssh @RUNTIME_PATH@/${target}/backupnode.slaves "/bin/sh -c 'mkdir -p @LOG_PATH@; mkdir -p @RUNTIME_PATH@; @EXEC_PATH@/backupnode -T -X $backupnode_remotedata %n %c %a %x $2 > @LOG_PATH@/backup_node_%n_${logpthtail}.log 2>&1'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$MAXTHREADS -b >> $logfile 2>&1
-
-        log "------------------------------"
-        log "Waiting for backup to complete"
-
-        log "nohup backupnode -W @RUNTIME_PATH@/${target}/backupnode.slaves $backupnode_data >> $logfile 2>&1 &"
-        nohup backupnode -W @RUNTIME_PATH@/${target}/backupnode.slaves $backupnode_data >> $logfile 2>&1
+        local fout=$(frunssh @RUNTIME_PATH@/${component}/${target}.slaves "killall backupnode 1>/dev/null 2>&1" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$MAXTHREADS -b 2>&1)
+        log "${header} ${fout}"
+        log "${header} frunssh @RUNTIME_PATH@/${component}/${target}.slaves \"/bin/sh -c 'mkdir -p @LOG_PATH@/${component}; mkdir -p @RUNTIME_PATH@; @EXEC_PATH@/backupnode -T -X $backupnode_remotedata %n %c %a %x $2 > @LOG_PATH@/${component}/${target}_backup_node_%n_${logpthtail}.log 2>&1'\" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$MAXTHREADS -b >> $logfile 2>&1"
+        local fout=$(frunssh @RUNTIME_PATH@/${component}/${target}.slaves "/bin/sh -c 'mkdir -p @LOG_PATH@/${component}; mkdir -p @RUNTIME_PATH@; @EXEC_PATH@/backupnode -T -X $backupnode_remotedata %n %c %a %x $2 > @LOG_PATH@/${component}/${target}_backup_node_%n_${logpthtail}.log 2>&1'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$MAXTHREADS -b 2>&1)
+        log "${header} ${fout}"
+        log "${header} Waiting for backup to complete"
+        log "${header} nohup backupnode -W @RUNTIME_PATH@/${component}/${target}.slaves $backupnode_data >> $logfile 2>&1 &"
+        nohup backupnode -W @RUNTIME_PATH@/${component}/${target}.slaves $backupnode_data >> $logfile 2>&1
         pid=`${PIDOF} backupnode`
-        log "backupnode process $pid still continuing"
+        log "${header} Backupnode process $pid still continuing"
     done
+}
+
+
+trap "pkill -P $$" SIGINT SIGTERM
+
+for target in ${thorlist[@]}; do
+    nohup backup ${target} &
 done
+
+wait
