HPCC-12923 Added sane logging/debugging to hpcc-init and component init files
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>

diff --git a/initfiles/bin/init_configesp b/initfiles/bin/init_configesp
--- a/initfiles/bin/init_configesp
+++ b/initfiles/bin/init_configesp
@@ -18,36 +18,48 @@
 
 PATH_PRE=`type -path hpcc_setenv`
 source ${PATH_PRE}
+source ${INSTALL_DIR}/etc/init.d/hpcc_common
 PID_NAME="$PID/`basename $PWD`.pid"
 
 INIT_PID_NAME="$PID/init_`basename $PWD`.pid"
 echo $$ > $INIT_PID_NAME
 
+component=`basename $PWD`
+export logfile="${LOG_DIR}/`basename $PWD`/${component}_init_`date +%Y_%m_%d_%H_%M_%S`.log"
+
 export SENTINEL="configesp.sentinel"
+log "Removing ---> ${SENTINEL}"
 rm -f ${SENTINEL}
-
-
 
 SNMPID=$$
 
 killed() {
+    log "attempting to kill $component"
     kill_process ${PID_NAME} configesp 3 ${SENTINEL}
+    if [[ $? -eq 1 ]]; then
+      log "could not kill $component"
+    else
+      log "Stopped $component"
+    fi
     exit 255
 }
 
 trap "killed" SIGINT SIGTERM SIGKILL
-
+log "calling configesp 1>/dev/null 2>/dev/null"
 nohup configesp 1>/dev/null 2>/dev/null &
 echo $! > $PID_NAME
 wait
+log "removing $PID_NAME"
 rm $PID_NAME
 
 while [ -e ${SENTINEL} ]; do
     sleep 5
     if [ -e ${SENTINEL} ]; then
+        log "calling configesp 1>/dev/null 2>/dev/null"
         nohup configesp 1>/dev/null 2>/dev/null &
         echo $! > $PID_NAME
         wait
+        log "removing $PID_NAME"
         rm $PID_NAME
     fi
 done
diff --git a/initfiles/bin/init_dafilesrv.in b/initfiles/bin/init_dafilesrv.in
--- a/initfiles/bin/init_dafilesrv.in
+++ b/initfiles/bin/init_dafilesrv.in
@@ -27,9 +27,9 @@ shift
 
 PATH_PRE=`type -path hpcc_setenv`
 source ${PATH_PRE}
+source ${INSTALL_DIR}/etc/init.d/hpcc_common
 PID_NAME="$PID/`basename $PWD`.pid"
 
-INSTANCE_NAME="`basename $PWD`"
 
 INIT_PID_NAME="$PID/init_`basename $PWD`.pid"
 echo $$ > $INIT_PID_NAME
@@ -37,29 +37,44 @@ echo $$ > $INIT_PID_NAME
 # this must match jsocket hard limit
 export handlelimit=32768
 
+component=`basename $PWD`
+export logfile="${LOG_DIR}/${component}/${component}_init_`date +%Y_%m_%d_%H_%M_%S`.log"
+
 export SENTINEL="dafilesrv.sentinel"
+log "Removing ${SENTINEL}"
 rm -f ${SENTINEL}
 
 killed(){
+    log "Attempting to kill $component"
     kill_process ${PID_NAME} dafilesrv 3 ${SENTINEL}
+    if [[ $? -eq 1 ]]; then
+      log "could not kill $component"
+    else
+      log "$component Stopped"
+    fi
     exit 255
 }
 
+log "Setting core and handle limit"
 ulimit -c unlimited
 ulimit -n $handlelimit
 
 trap "killed" SIGINT SIGTERM SIGKILL
-dafilesrv -L $log -I ${INSTANCE_NAME} &
+log "Calling dafilesrv -L $log -I $component &"
+dafilesrv -L $log -I $component &
 echo $! > $PID_NAME
 wait
+log "Removing $PID_NAME"
 rm $PID_NAME
 
 while [ -e ${SENTINEL} ]; do
     sleep 5
     if [ -e ${SENTINEL} ]; then
-        dafilesrv -L $log -I ${INSTANCE_NAME} &
+        log "Calling dafilesrv -L $log -I $component &"
+        dafilesrv -L $log -I $component &
         echo $! > $PID_NAME
         wait
+        log "Removing $PID_NAME"
         rm $PID_NAME
     fi
 done
diff --git a/initfiles/bin/init_eclagent.in b/initfiles/bin/init_eclagent.in
--- a/initfiles/bin/init_eclagent.in
+++ b/initfiles/bin/init_eclagent.in
@@ -19,36 +19,50 @@
 
 PATH_PRE=`type -path hpcc_setenv`
 source ${PATH_PRE}
+source ${INSTALL_DIR}/etc/init.d/hpcc_common
 PID_NAME="$PID/`basename $PWD`.pid"
 
 INIT_PID_NAME="$PID/init_`basename $PWD`.pid"
 echo $$ > $INIT_PID_NAME
 
+component=`basename $PWD`
+export logfile="${LOG_DIR}/${component}/${component}_init_`date +%Y_%m_%d_%H_%M_%S`.log"
+
 export SENTINEL="agentexec.sentinel"
+log "Removing $SENTINEL"
 rm -f ${SENTINEL}
 
+log "Removing $PID_DIR/hthortemp/*"
 rm -f ${PID_DIR}/hthortemp/*
 
 killed (){
+    log "Attempting to kill $component"
     kill_process ${PID_NAME} agentexec 3 ${SENTINEL}
+    if [[ $? -eq 1 ]]; then
+      log "could not kill $component"
+    else
+      log "$component Stopped"
+    fi
     exit 255
 }
 
 
 trap "killed" SIGINT SIGTERM SIGKILL
-
-
+log "Calling agentexec 1>/dev/null 2>/dev/null &"
 agentexec 1>/dev/null 2>/dev/null &
 echo $! > $PID_NAME
 wait
+log "Removing $PID_NAME"
 rm $PID_NAME
 
 while [ -e ${SENTINEL} ]; do
     sleep 1
     if [ -e ${SENTINEL} ]; then
+        log "Calling agentexec 1>/dev/null 2>/dev/null &"
         agentexec 1>/dev/null 2>/dev/null &
         echo $! > $PID_NAME
         wait
+        log "Removing $PID_NAME"
         rm $PID_NAME
     fi
 done
diff --git a/initfiles/bin/init_roxie b/initfiles/bin/init_roxie
--- a/initfiles/bin/init_roxie
+++ b/initfiles/bin/init_roxie
@@ -17,18 +17,25 @@
 
 PATH_PRE=`type -path hpcc_setenv`
 source ${PATH_PRE}
+source ${INSTALL_DIR}/etc/init.d/hpcc_common
 PID_NAME="$PID/`basename $PWD`.pid"
 
 INIT_PID_NAME="$PID/init_`basename $PWD`.pid"
 echo $$ > $INIT_PID_NAME
 
+component=`basename $PWD`
+export logfile="${LOG_DIR}/${component}/${component}_init_`date +%Y_%m_%d_%H_%M_%S`.log"
+
 export SENTINEL="roxie.sentinel"
+log "Removing $SENTINEL"
 rm -f ${SENTINEL}
 
 if [ -n "$1" ]; then
+    log "cd $1"
     cd $1
 fi
 
+log "sourcing roxievars"
 . ./roxievars
 
 if [ -n "$2" ]; then
@@ -40,31 +47,44 @@ fi
 export LIBC_FATAL_STDERR_=1
 export restarts=0
 
+log "Setting limits for core and open file descriptors"
 ulimit -c unlimited
 ulimit -n $NUM_ROXIE_HANDLES
 
 killed() {
     if [ -n "$1" ]; then
+        log "cd $1"
         cd $1
     fi
+    log "Attempting to kill $component"
     kill_process ${PID_NAME} roxie 3 ${SENTINEL}
+    if [[ $? -eq 1 ]]; then
+      log "could not kill $component"
+    else
+      log "$component Stopped"
+    fi
     exit 255
 }
 
 trap "killed" SIGINT SIGTERM SIGKILL
-nohup roxie --topology=RoxieTopology.xml --logfile=$logfilename --restarts=$restarts --stdlog=0 2>>$logfilename.stderr 1>>$logfilename.stdout &
+log "Calling nohup roxie --topology=RoxieTopology.xml --logfile --restarts=$restarts --stdlog=0 2>>$logfilename.stderr 1>>$logfilename.stdout &"
+nohup roxie --topology=RoxieTopology.xml --logfile --restarts=$restarts --stdlog=0 2>>$logfilename.stderr 1>>$logfilename.stdout &
 echo $! > $PID_NAME 
 wait
+log "Removing $PID_NAME"
 rm $PID_NAME
 
 # Automatically restart roxie when it dies
 while [ -e ${SENTINEL} ]; do
     export restarts=$(($restarts+1))
+    log "Restarting $restarts"
     echo Restarting $restarts >> $logfilename.stderr
     echo Restarting $restarts >> $logfilename.stdout
-    nohup roxie --topology=RoxieTopology.xml --logfile=$logfilename --restarts=$restarts --stdlog=0 2>>$logfilename.stderr 1>>$logfilename.stdout &
+    log "Calling nohup roxie --topology=RoxieTopology.xml --logfile --restarts=$restarts --stdlog=0 2>>$logfilename.stderr 1>>$logfilename.stdout &"
+    nohup roxie --topology=RoxieTopology.xml --logfile --restarts=$restarts --stdlog=0 2>>$logfilename.stderr 1>>$logfilename.stdout &
     echo $! > $PID_NAME
     wait
+    log "Removing $PID_NAME"
     rm $PID_NAME
 done
 
