Modifications to pid.sh and hpcc_common.in
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>

diff --git a/initfiles/bash/etc/init.d/hpcc_common.in b/initfiles/bash/etc/init.d/hpcc_common.in
--- a/initfiles/bash/etc/init.d/hpcc_common.in
+++ b/initfiles/bash/etc/init.d/hpcc_common.in
@@ -390,16 +390,19 @@ startCmd() {
     logDir=$log/${compName}
 
     if [ ${noStatusCheck} -ne 1 ]; then
-      check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
+      check_status ${PIDPATH} ${COMPPIDPATH} 1
       RCSTART=$?
       if [[ ${RCSTART} -eq 3 ]];then
         # take care of failure message in check_status function
         kill_process $COMPPIDPATH "unknown" 15 1
-      fi
-      if [[ ${RCSTART} -eq 0 || ${RCSTART} -eq 2 ]]; then
+        if [[ $? -eq 1 ]]; then
+            log "Failed to clean up orphaned process"
+            return 1
+        fi
+      elif [[ ${RCSTART} -eq 0 || ${RCSTART} -eq 2 ]]; then
         #Since component is already started but current script is failed till returning 0
         log "$compName ---> already started"
-        log_success_msg "Already Started"
+        log_success_msg
         return ${RCSTART}
       fi
     fi
@@ -438,22 +441,7 @@ startCmd() {
 
     log "${startcmd}"
 
-    # Creating a Lock
-    lockPath=${lock}/${compName}
-    if [ ! -d $lockPath ]; then
-        mkdir -p $lockPath >>/dev/null 2>&1
-    fi
-    chown -c $user:$group $lockPath >> /dev/null 2>&1
-    lock ${lock}/${compName}/${compName}.lock
-
-    if [ $__lockCreated -eq 0 ]; then
-        log "Cannot create the lock file. File locked by subsystem"
-        log_failure_msg "Cannot create the lock file, File locked by subsystem"
-        return 3
-    fi
-
     eval $startcmd
-
 
     local WAITTIME=120
     local RCSTART=0
@@ -464,27 +452,18 @@ startCmd() {
       SENTINEL_CHECK=0
     fi
 
-    while [ ${WAITTIME} -gt 0 ]
-    do
-        WAITTIME=`expr ${WAITTIME} - 1`
-        check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} ${SENTINEL_CHECK}
+    while [[ ${WAITTIME} -gt 0 ]]; do
+        ((WAITTIME--))
+        check_status ${PIDPATH} ${COMPPIDPATH} ${SENTINEL_CHECK}
         RCSTART=$?
-        if [ ${RCSTART} -eq 0 ]; then
-          log_success_msg
-          return 0;
-        elif [ ${RCSTART} -eq 2 ]; then
-          COMPONENT_HAS_STARTED=1
-        else
-          if [ ${COMPONENT_HAS_STARTED} -eq 1 ]; then
-            log "${compName} failed to start cleanly"
-            log_failure_msg "${compName} failed to start cleanly"
+        if [[ ${RCSTART} -eq 0 ]]; then
+            log_success_msg
             return 0;
-          fi
         fi
         sleep 1
     done
 
-    if [ ${WAITTIME} -eq 0 ]; then
+    if [[ ${WAITTIME} -eq 0 && $RCSTART -eq 2 ]]; then
         log_timeout_msg
         log "${compName} has timed out, but may still be starting"
     fi
@@ -502,49 +481,56 @@ stop_component() {
     ## not running but associated pidfile and/or lockfiles do exist.
     ###
     FAILED=0
-    check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 0
+    check_status ${PIDPATH} ${COMPPIDPATH} 0
     RCSTOP=$?
-    if [ $RCSTOP -ne 0 ];then
+    if [[ $RCSTOP -eq 1 ]];then
       log "Already stopped"
-      log_success_msg "Already stopped"
-      cleanup_component
+      log_success_msg
       cleanupRuntimeEnvironment
       return 0
-    fi
-
-    stopcmd="${START_STOP_DAEMON} -K -p ${PIDPATH} >> tmp.txt 2>&1"
-    log "$stopcmd"
-
-    eval $stopcmd
-
-    unlock ${LOCKPATH}
-
-    RESULT=0
-    local waittime=30
-    [[ $compType = "dali" ]] && waittime=720
-    while [[ $RESULT -ne 1 && $waittime -gt 0 ]]; do
-        check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 0
-        RESULT=$?
-        ((waittime--))
-        if ! ((waittime % 60)); then
-            echo "still stopping ..."
-        fi
-        [[ $RESULT -ne 1 ]] && sleep 1
-    done
-
-    if [[ $RESULT -ne 1 ]]; then
-        if [[ $waittime -eq 0 ]]; then
-            log_failure_msg "Process may still be attempting to shut down cleanly"
-        else
+    elif [[ $RCSTOP -eq 3 ]]; then
+        log "ERROR:  Orphaned process"
+        kill_process $COMPPIDPATH "unknown" 15 1
+        if [[ $? -eq 1 ]]; then
+            log "unable to clean up orphan"
             log_failure_msg
+            return 1
+        else
+            log "cleaned up orphan"
+            log_success_msg
+            return 0
         fi
     else
-        log_success_msg
-    fi
-    cleanupRuntimeEnvironment
-    RCSTOP=0
+        stopcmd="${START_STOP_DAEMON} -K -p ${PIDPATH} >> tmp.txt 2>&1"
+        log "$stopcmd"
 
-    return ${RCSTOP}
+        eval $stopcmd
+
+        RESULT=0
+        local waittime=30
+        [[ $compType = "dali" ]] && waittime=720
+        while [[ $RESULT -ne 1 && $waittime -gt 0 ]]; do
+            check_status ${PIDPATH} ${COMPPIDPATH} 0
+            RESULT=$?
+            ((waittime--))
+            if ! ((waittime % 60)); then
+                echo "still stopping ..."
+            fi
+            [[ $RESULT -ne 1 ]] && sleep 1
+        done
+
+        if [[ $RESULT -ne 1 ]]; then
+            if [[ $waittime -eq 0 ]]; then
+                log_failure_msg "Process may still be attempting to shut down cleanly"
+            else
+                log_failure_msg
+            fi
+        else
+            log_success_msg
+        fi
+        cleanupRuntimeEnvironment
+        return 0
+    fi
 }
 
 
@@ -591,7 +577,7 @@ restart_component() {
       fi
       /etc/init.d/dafilesrv start 2>/dev/null
     else
-      check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
+      check_status ${PIDPATH} ${COMPPIDPATH} 1
       RCRESTART=$?
       if [ $RCRESTART -ne 0 ];then
         log  "$compName ---> Stopped.  Now Starting ..."
@@ -601,14 +587,14 @@ restart_component() {
         stop_component ${compName}
       fi
       start_component $compName
-      check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
+      check_status ${PIDPATH} ${COMPPIDPATH} 1
       RCRESTART=$?
       return $RCRESTART
     fi
 }
 
 status_component() {
-  check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
+  check_status ${PIDPATH} ${COMPPIDPATH} 1
   RCSTATUS=$?
   getPid ${COMPPIDPATH}
   if [ ${RCSTATUS} -ne 0 ];then
@@ -912,13 +898,14 @@ kill_process()
     local PROCESS=$2
     local TIMEOUT=$3
     if [[ $# -eq 4 ]]; then
-        SENTINEL=$4
         removeSentinelFile
     fi
     if [[ -e $PID ]]; then
         pidwait_fn $PID $PROCESS $TIMEOUT
         local RC_PIDWAIT=$?
         return $RC_PIDWAIT
+    else
+        return 1
     fi
 }
 
