Altered check_status and moved kill_process
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>

diff --git a/initfiles/bash/etc/init.d/hpcc_common.in b/initfiles/bash/etc/init.d/hpcc_common.in
--- a/initfiles/bash/etc/init.d/hpcc_common.in
+++ b/initfiles/bash/etc/init.d/hpcc_common.in
@@ -392,11 +392,11 @@ startCmd() {
     if [ ${noStatusCheck} -ne 1 ]; then
       check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
       RCSTART=$?
-      if [ ${RCSTART} -gt 1 ];then
+      if [[ ${RCSTART} -eq 3 ]];then
         # take care of failure message in check_status function
-        cleanupRuntimeEnvironment
+        kill_process $COMPPIDPATH "unknown" 15 1
       fi
-      if [ ${RCSTART} -eq 0 ]; then
+      if [[ ${RCSTART} -eq 0 || ${RCSTART} -eq 2 ]]; then
         #Since component is already started but current script is failed till returning 0
         log "$compName ---> already started"
         log_success_msg "Already Started"
@@ -888,7 +888,8 @@ run_cluster() {
 ## Usage: cluster_tools_init
 ##    Initialization for cluster tools
 ##
-cluster_tools_init() {
+cluster_tools_init()
+{
 
    set_environmentvars
 
@@ -905,62 +906,51 @@ cluster_tools_init() {
    [ "$cluster_log_dir_owner" != "${user}" ] && ${_cmd_prefix} chown ${user}:${user} $CLUSTER_LOG_DIR
 }
 
-##
-## Cleanup component
-##
-cleanup_component() {
+kill_process()
+{
+    local PID=$1
+    local PROCESS=$2
+    local TIMEOUT=$3
+    if [[ $# -eq 4 ]]; then
+        SENTINEL=$4
+        removeSentinelFile
+    fi
+    if [[ -e $PID ]]; then
+        pidwait_fn $PID $PROCESS $TIMEOUT
+        local RC_PIDWAIT=$?
+        return $RC_PIDWAIT
+    fi
+}
 
-  # used to get variables for frunssh
-  # Necessary for when we source in setvars, since we aren't using the start-stop-demon the $HOME will
-  # be set to /root or some other location, and not the appropriate directory, causing problems
-  # with $SSHidentityfile
-  set_environmentvars
-  HOME=${home}/${user}
-  instancedir=${runtime}/${compName}
-  if [ -e $instancedir/setvars ]; then
-    source $instancedir/setvars
-  fi
+pidwait_fn()
+{
+    local PID=$1
+    getPid $PID
+    local WATCH_PID=$?
+    local PROCESS=$2
+    local TIMEOUT=$(($3*1000))
 
-  # grab the PID of our component, and in the case it doesn't exist, the pid of the init file (in case
-  # it somehow is still alive)
-  local cpidpath=${COMPPIDPATH}
-  if [ "${compType}" = "thor" ] && [ ! -f "${cpidpath}" ]; then
-    # if run_thor is sent a SIGKILL, the normal COMPPIDPATH file will no longer exist, we catch this and
-    # fall back to the {compName}_master.pid file that will still be available.
-    cpidpath=$( echo $cpidpath | sed 's/\.pid/_master.pid/' )
-  fi
-  getPid ${cpidpath}
-  local mpid=$__pidValue
-  if [ $mpid -eq 0 ]; then
-    getPid ${PIDPATH}
-    mpid=$__pidValue
-  fi
+    if [[ $PROCESS != "unknown" ]] && ps -p $WATCH_PID -o command= | grep -v "${PROCESS}" &>/dev/null; then
+        return 0
+    fi
 
-  # start with SIGTERM and then follow up with SIGKILL if unsuccessful
-  if [ $mpid -ne 0 ] ; then
-    # use the mpid we collected to grab the group pid of the process, to kill off all siblings at once
-    local pgid=$( ps -p $mpid -o pid,pgid | grep $mpid | awk '{ print $2 }' )
-
-    kill -15 -$pgid
-    sleep 1
-    local WAITTIME=5
-    local RUNNING=1
-    while [[ ${WAITTIME} -gt 0 ]]; do
-      WAITTIME=`expr ${WAITTIME} - 1`
-      kill -0 -$pgid &> /dev/null
-      if [ $? -ne 0 ];then
-        log "${compName} orphans cleaned up"
-        RUNNING=0
-        break;
-      else
-        log "Waiting for ${compName} orphans to cleanup gracefully"
-        sleep 1
-      fi
+    kill $WATCH_PID > /dev/null 2>&1
+    while [[ -d /proc/$WATCH_PID ]] && [[ $TIMEOUT -gt 0 ]]; do
+        sleep 0.2
+        local TIMEOUT=$(($TIMEOUT-200))
     done
 
-    if [[ ${RUNNING} -eq 1 ]]; then
-      log "sending SIGKILL to ${compName} orphans"
-      kill -9 -$pgid
+    if [[ $TIMEOUT -le 0 ]] && ([[ $PROCESS == "unknown" ]] || ps -p $WATCH_PID -o command= | grep -v "${PROCESS}" &>/dev/null) ; then
+        log "Failed to kill ${PROCESS} process gracefully, sending SIGKILL"
+        kill -9 $WATCH_PID &>/dev/null
+        sleep 1
+        kill -0 $WATCH_PID &>/dev/null
+        # if still alive
+        if [[ $? -eq 0 ]]; then
+            return 1
+        fi
     fi
-  fi
+
+    removePid $PID
+    return 0
 }
