HPCC-15142 Changes to configure_file from processor
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

diff --git a/initfiles/sbin/hpcc_common.in b/initfiles/sbin/hpcc_common.in
--- a/initfiles/sbin/hpcc_common.in
+++ b/initfiles/sbin/hpcc_common.in
@@ -24,9 +24,7 @@
 ## $1="<path to ini file>"
 ####
 
-###<REPLACE>###
-
-START_STOP_DAEMON=${INSTALL_DIR}/bin/start-stop-daemon
+START_STOP_DAEMON=@ABS_EXEC_PATH@/start-stop-daemon
 
 which_service(){
     SERV=`type --path service`
@@ -52,10 +50,10 @@ which_pidof(){
     fi
 }
 
-source  ${INSTALL_DIR}/etc/init.d/lock.sh
-source  ${INSTALL_DIR}/etc/init.d/pid.sh
-source  ${INSTALL_DIR}/etc/init.d/init-functions
-source  ${INSTALL_DIR}/etc/init.d/export-path
+source  @ABS_SBIN_PATH@/hpcc_lock
+source  @ABS_SBIN_PATH@/hpcc_pid
+source  @ABS_SBIN_PATH@/hpcc_init_functions
+source  @ABS_SBIN_PATH@/hpcc_export_path
 
 
 cfg.parser () {
@@ -245,19 +243,21 @@ strstr() {
 }
 
 set_environmentvars() {
-    HPCC_CONFIG=${HPCC_CONFIG:-${CONFIG_DIR}/${ENV_CONF_FILE}}
+    HPCC_CONFIG=${HPCC_CONFIG:-@ABS_CONF_PATH@/@ENV_CONF_FILE@}
 
     ## Retrieve the Section to use from environment variable and if not set
     ## use default of "DEFAULT"
     ##
     SECTION=${SECTION:-DEFAULT}
 
+    set VERBOSE=1
     cfg.parser ${HPCC_CONFIG}
     cfg.section.${SECTION}
 
     if [ -n "${umask}" ]; then
         umask $umask
     fi
+    unset VERBOSE
 }
 
 
@@ -272,8 +272,8 @@ set_componentvars() {
 }
 
 validate_configuration() {
-    if ! validation_error=$(${configgen_path}/configgen -env ${envfile} -validateonly 2>&1); then
-        log  "get_commondirs(): validation failure ${envfile}"
+    if ! validation_error=$(@ABS_SBIN_PATH@/configgen -env @ABS_CONF_PATH@/@ENV_XML_FILE@ -validateonly 2>&1); then
+        log  "get_commondirs(): validation failure @ABS_CONF_PATH@/@ENV_XML_FILE@"
         log  "${validation_error}"
         echo -e "\033[31merror\033[0m: configgen xml validation failure"
         exit 1
@@ -283,7 +283,7 @@ validate_configuration() {
 get_commondirs() {
     componentFile="${path}/componentfiles/configxml"
     validate_configuration
-    DIRS=$(${configgen_path}/configgen -env ${envfile} -id ${componentFile} -listcommondirs)
+    DIRS=$(@ABS_SBIN_PATH@/configgen -env @ABS_CONF_PATH@/@ENV_XML_FILE@ -id ${componentFile} -listcommondirs)
     rc=$?
     if [[ $rc -ne 0 ]]; then
         log  "get_commondirs(): failure in configgen call"
@@ -300,7 +300,7 @@ configGenCmd() {
     logDir=$log/${compName}
 
     validate_configuration
-    configcmd="${configgen_path}/configgen -env ${envfile} -od ${runtime} -id ${componentFile} -c ${compName}"
+    configcmd="@ABS_SBIN_PATH@/configgen -env @ABS_CONF_PATH@/@ENV_XML_FILE@ -od ${runtime} -id ${componentFile} -c ${compName}"
     log "$configcmd"
     if [ "$(whoami)" != "${user}" ]; then
         su ${user} -c "$configcmd" 2>/dev/null
@@ -390,12 +390,12 @@ cleanupRuntimeEnvironment() {
 
 
 start_dafilesrv() {
-   /etc/init.d/dafilesrv status 1>/dev/null 2>/dev/null
+   @ABS_INIT_PATH@/dafilesrv status 1>/dev/null 2>/dev/null
    if [ $? -ne 0 ];then
       #Dafilesrv is not running so start it , before starting cleanup the lock and pid file.
       cleanupRuntimeEnvironment
       noStatusCheck=1
-      /etc/init.d/dafilesrv setup 1>/dev/null 2>/dev/null
+      @ABS_INIT_PATH@/dafilesrv setup 1>/dev/null 2>/dev/null
       startCmd ${compName} ${noStatusCheck}
       return $?
    else
@@ -492,7 +492,7 @@ startCmd() {
         UMASK_ARG="--umask ${umask}"
     fi
 
-    EXEC_COMMAND="${bin_path}/init_${compType} "
+    EXEC_COMMAND="@ABS_EXEC_PATH@/init_${compType} "
     startcmd="${START_STOP_DAEMON} -S -p ${pid}/init_${compName}.pid -c ${user}:${group} -d ${compPath} ${UMASK_ARG} -m -x ${EXEC_COMMAND} -b"
 
     log "${startcmd}"
@@ -546,7 +546,7 @@ startCmd() {
     log_timeout_msg
     log "${compName} has timed out, but may still be starting"
 
-    chmod 644 ${envfile}
+    chmod 644 @ABS_CONF_PATH@/@ENV_XML_FILE@
 
     return ${RCSTART}
 }
@@ -557,7 +557,7 @@ stop_component() {
     cd ${compPath}
 
     if [[ -e "${PIDPATH}" ]]; then
-        stopcmd="${START_STOP_DAEMON} -K -p ${PIDPATH} >> tmp.txt 2>&1"
+        stopcmd="${START_STOP_DAEMON} -K -p ${PIDPATH} > /dev/null 2>&1"
         log "$stopcmd"
         eval $stopcmd
 
@@ -597,7 +597,7 @@ start_component() {
     logDir=$log/${compName}
 
     if [ ! -d $logDir ]; then
-        mkdir -p $logDir >> tmp.txt 2>&1
+        mkdir -p $logDir > /dev/null 2>&1
         chown -c $user:$group $logDir >> /dev/null 2>&1
     fi
 
@@ -619,15 +619,15 @@ start_component() {
 
 restart_component() {
     if strstr "${compType}" "dafilesrv" ;then
-      /etc/init.d/dafilesrv status 1>/dev/null 2>/dev/null
+      @ABS_INIT_PATH@/dafilesrv status 1>/dev/null 2>/dev/null
       if [ $? -eq 0 ];then
-        /etc/init.d/dafilesrv stop 2>/dev/null
+        @ABS_INIT_PATH@/dafilesrv stop 2>/dev/null
       else
         log  "$compName ---> Stopped.  Now Starting ..."
         echo "Component $compName was not running. Will start it now for you ..."
         cleanupRuntimeEnvironment
       fi
-      /etc/init.d/dafilesrv start 2>/dev/null
+      @ABS_INIT_PATH@/dafilesrv start 2>/dev/null
     else
       check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
       RCRESTART=$?
@@ -689,7 +689,7 @@ setup_component() {
 
 create_dropzone() {
     validate_configuration
-    dropzones=$(${configgen_path}/configgen -env ${envfile} -listdirs)
+    dropzones=$(@ABS_SBIN_PATH@/configgen -env @ABS_CONF_PATH@/@ENV_XML_FILE@ -listdirs)
     rc=$?
     if [[ $rc -ne 0 ]]; then
         log  "create_dropzone(): failure in configgen call"
@@ -861,7 +861,7 @@ run_cluster() {
 
     if [[ -z "$3" ]]; then
         validate_configuration
-        t_IP=$(${INSTALL_DIR}/sbin/configgen -env ${CONFIG_DIR}/${ENV_XML_FILE} -machines)
+        t_IP=$(@ABS_SBIN_PATH@/configgen -env @ABS_CONF_PATH@/@ENV_XML_FILE@ -machines)
         rc=$?
         if [[ $rc -ne 0 ]]; then
             log  "run_cluster(): failure in configgen call"
@@ -902,8 +902,8 @@ run_cluster() {
    _num_failed=0
    _num_processed=0
    _pregress=0
-   _log_file=${LOG_DIR}/cluster/se_$(basename $_cmd)_$(date +%Y%m%d_%H%M%S).log
-   [ ! -d ${LOG_DIR}/cluster ] && mkdir -p ${LOG_DIR}/cluster
+   _log_file=@ABS_LOG_PATH@/@DIR_NAME@/cluster/se_$(basename $_cmd)_$(date +%Y%m%d_%H%M%S).log
+   [ ! -d @ABS_LOG_PATH@/@DIR_NAME@/cluster ] && mkdir -p @ABS_LOG_PATH@/@DIR_NAME@/cluster
    [ -e $_log_file ] && rm -rf $_log_file
    if [ "$RUN_CLUSTER_DISPLAY_OUTPUT" != "TRUE" ]
    then
@@ -958,8 +958,8 @@ cluster_tools_init() {
    [ "$(id -u)" != "0" ] && _cmd_prefix=sudo
 
    # Check and set log directory
-   CLUSTER_LOG_DIR=${LOG_DIR}/cluster
-   [ ! -d $LOG_DIR ]  && ${_cmd_prefix} /etc/init.d/hpcc-init status > /dev/null 2>&1
+   CLUSTER_LOG_DIR=@ABS_LOG_PATH@/@DIR_NAME@/cluster
+   [ ! -d @ABS_LOG_PATH@/@DIR_NAME@ ]  && ${_cmd_prefix} @ABS_INIT_PATH@/hpcc-init status > /dev/null 2>&1
 
    [ ! -d $CLUSTER_LOG_DIR ] && mkdir -p $CLUSTER_LOG_DIR
    # workaround inconsistency of stat command
